#!/bin/sh

myscript_dir=/usr/local/bin/myscripts

desc() {
    path=$myscript_dir/$1
    line=`sed -n 2p $path`
    match=`echo $line|grep -c -i -P '#\s?encoding\s?='`
    if [ $match -gt 0 ];then         
        line=$(sed -n 3p $path)
    fi
    printf "\033[34m%-20s" $1
    echo "\033[33m$line"
}

usage() {
    echo "Usage: \033[32m$(basename $0) command_name [options]"
    echo "\033[0mHelp: "
    echo "\033[34m help  (h)       \033[33mshow this help (also, --h, -h)"
    echo "\033[34m list  (l)       \033[33mshow all available commands"
    echo "\033[34m -     ll        \033[33mshow all available commands, long format"
    echo "\033[34m -     la        \033[33mshow all available commands, full format"
    echo "\033[34m info  (n)       \033[33mshow command description"
    echo "\033[34m edit  (e)       \033[33medit my script"
    echo "\033[34m del   (d)       \033[33mdelete a script, also 'delete'"
    echo "\033[34m cat   (c)       \033[33mprint script source code"
    echo "\033[34mwhich  (w)       \033[33mshow script path"
    echo "\033[34mchmodx (x)       \033[33mmake script executable\033[0m"
    exit 0
}

if [ $# -lt 1 ]; then
    usage
else
    cmd=$1
    shift 1
    if [ "$cmd" == "list" ] || [ "$cmd" == "l" ] ; then
        ls -G $myscript_dir
    elif [ "$cmd" == "ll" ] ; then
        ls -lG $myscript_dir
    elif [ "$cmd" == "la" ] || [ "$cmd" == "al" ] ; then
        ls -laG $myscript_dir
    elif [ "$cmd" == "info" ] || [ "$cmd" == "n" ]; then
        if [ $# -eq 0 ]; then
            echo "Available commands:"
            for file in `ls -1 $myscript_dir`;do
                desc $file
            done
        else
            if [ -f $myscript_dir/$1 ]; then
                desc $1
            else
                echo "No such command."
            fi
        fi
    elif [ "$cmd" == "edit" ] || [ "$cmd" == "e" ] ; then
        if [ $# -eq 0 ]; then
            mate /usr/local/bin/my
        else
            for script in $*;do
                mate $myscript_dir/$script
            done
            unset script
        fi
    elif [ "$cmd" == "delete" ] || [ "$cmd" == "d" ] || [ "$cmd" == "del" ] ; then
        if [ $# -eq 0 ]; then
            exit 0
        else
            for script in $*;do
                printf "\033[31mAre you sure to delete script '$script'? (yes/no): \033[0m"
                read answer
                answer=$(echo $answer | tr '[A-Z]' '[a-z]')
                if [ -z "$answer" ];then
                    answer=no
                fi
                if [ ${answer} == "yes" ];then
                    if [ -f $myscript_dir/$script ]; then
                        rm $myscript_dir/$script
                    else
                        echo ${script} does not exists.
                    fi
                    
                fi
            done
            unset script
        fi
    elif [ "$cmd" == "which" ] || [ "$cmd" == "w" ]; then
        if [ $# -eq 0 ]; then
            echo /usr/local/bin/my
        else
            for script in $*;do
                filename=$myscript_dir/$script
                if [ -e $filename ]; then
                    echo $filename
                fi
            done
        fi
        unset script
    elif [ "$cmd" == "cat" ] || [ "$cmd" == "c" ]; then
        if [ $# -eq 0 ]; then
            cat /usr/local/bin/my | less
        else
            for script in $*;do
                filename=$myscript_dir/$script
                if [ -e $filename ]; then
                    cat $filename | less
                fi
            done
        fi
        unset script
    elif [ "$cmd" == "help" ] || [ "$cmd" == "h" ] || [ "$cmd" == "--help" ] || [ "$cmd" == "-h" ]; then
        usage
    elif [ "$cmd" == "chmodx" ] || [ "$cmd" == "x" ]; then
        for script in $*;do
            filename=$myscript_dir/$script
            if [ -e $filename ]; then
                chmod +x $filename
            fi
        done
        unset script
    else
        if [ -f $myscript_dir/$cmd ]; then
            if [ $# -lt 1 ]; then
                $myscript_dir/$cmd
            else
                $myscript_dir/$cmd "$@"
            fi
        else
            echo "No such command.\nUse 'my help' for help."
        fi
    fi
fi

unset myscript_dir
