#!/usr/bin/env ruby
def show_usage
  puts "Usage: my #{File.basename $0} on|off"
end

if ARGV.size != 1
  show_usage
  exit 1
else
  if ARGV[0].downcase == "on"
    system("defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1")
  elsif ARGV[0].downcase == "off"
    system("defaults write com.apple.NetworkBrowser BrowseAllInterfaces 0")
  else
    show_usage
  end
end