#!/bin/sh
echo redcrane_18p2p.com_touch99.com_waikeung.org_karayou.com_tvboxnow.com_FDZone.ORG_sexinsex.net_share
echo redcrane_18p2p.com_touch99.com_waikeung.org_share
echo redcrane_18p2p.com_touch99.com_redcrane186.blogspot.com
echo redcrane186.blogspot.com