#!/usr/bin/env ruby
# Turn on and off FTP service on OSX Lion.

def show_usage
  puts "Usage: my #{File.basename $0} on|off"
end

if ARGV.size != 1
  show_usage
  exit 1
else
  if ARGV[0].downcase == "on"
    system("sudo -s launchctl load -w /System/Library/LaunchDaemons/ftp.plist")
  elsif ARGV[0].downcase == "off"
    system("sudo -s launchctl unload -w /System/Library/LaunchDaemons/ftp.plist")
  else
    show_usage
  end
end