#!/bin/bash
# Inject f-script into a running application

usage() {
    echo Usage: my `basename $0` Process_Name
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

pid=$(pidof $1 | awk -F' ' '{print $1}')
if [ -z $pid ];then
    echo No such process: $1
    exit 255
fi
cat > /tmp/run_gdb << EOF
sudo -u `whoami` gdb --pid $pid --batch --nx --command=/dev/stdin << EOT
p (char)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScript.framework"] load]
p (void)[FScriptMenuItem insertInMainMenu]
EOT
EOF
osascript -e "tell application \"System Events\"
    set pid to $pid
end tell
do shell script \"sh /tmp/run_gdb \" & pid"
unset pid
