#!/usr/bin/env ruby
# Turn on and off OSX Lion's key repeat feature.

if ARGV.size < 1
  puts "Usage: my #{File.basename $0} on|off"
  puts
  puts "This script turns on and off the OSX lion's key repeat."
  puts "Turn on to enable key repeat."
  puts "Turn off to enable key hold to input euro chars."
  exit 1
end

if ARGV[0].downcase == "on"
  system("defaults write -g ApplePressAndHoldEnabled -bool false")
else
  system("defaults write -g ApplePressAndHoldEnabled -bool true")
end