#!/usr/bin/env ruby
# Pack git repo into a zip archive for sharing.

require "fileutils"
include FileUtils

(puts "Usage: my #{File.basename(__FILE__)} folder1 [folder2 ...]";exit) if ARGV[0].nil?

ARGV.each do |f|
  next unless File.directory?(f)
  folder = f.strip
  timestamp = Time.now.strftime("%Y%m%d%H%M%S")
  new_folder = folder + "_" + timestamp
  print "Zipping #{folder}..."
  cp_r folder, new_folder
  cd new_folder do
    rm_rf ".git" if File.exists?(".git")
    rm ".gitignore" if File.exists?(".gitignore")
  end
  system("zip -9 -r #{new_folder}.zip #{new_folder} > /dev/null 2>&1")
  rm_rf new_folder
  puts "done!"
end
