#!/usr/bin/env ruby
# Sync and push myscripts to github.

require "FileUtils"
include FileUtils

script_dir = "/usr/local/bin"
dest_dir = "/Volumes/Data/Developer.localized/github/myscripts/"

cd script_dir do
  cp "my", dest_dir
  cp_r "myscripts", dest_dir
end

cd dest_dir do
  message = "Updated at #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"
  message = ARGV.join(" ") if ARGV.size > 0
  system "my commit -p \"#{message}\""
end