#!/usr/bin/env ruby
# Sync and push myscripts to github.

require "FileUtils"
include FileUtils

script_dir = "/usr/local/bin"
dest_dir = "/Volumes/Data/Developer.localized/github/myscripts/"

scripts_arr = dest_arr = []
cd script_dir do
  cp "my", dest_dir
  cp_r "myscripts", dest_dir
  cd "myscripts" do
    scripts_arr = Dir["*"].to_a
  end
end

cd dest_dir do
  cd "myscripts" do
    scripts_arr = Dir["*"].to_a
    (scripts_arr & dest_arr).each { |f| puts f }
    #puts Dir["*"].to_a;exit
  end
  if ARGV.size == 0
    message = "Updated at #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"
    system "my commit -p \"#{message}\""
  elsif ARGV[0] == "-p" && ARGV.size > 1
    argv = ARGV;argv.shift
    message = argv.join(" ")
    system "my commit -p \"#{message}\""
  else
    system "git #{ARGV.join(' ')}"
  end
end
