#!/bin/sh
# Update script for users.

cdir=$(pwd)
curl -sLO https://github.com/venj/myscripts/zipball/master 
unzip -q master
cd venj-myscripts-*
adir=$(basename $(pwd))
cp my /usr/local/bin/my
mkdir -p /usr/local/bin/myscripts
cp -rf myscripts /usr/local/bin/myscripts
cd $cdir
rm -rf $adir
rm master
