#!/bin/sh
# Update script for users.

cdir=$(pwd)
curl -sLO https://github.com/venj/myscripts/archive/master.zip
unzip -q master.zip
cd myscripts-master
adir=$(basename $(pwd))
cp my /usr/local/bin/my
cp -rf myscripts /usr/local/bin
cd $cdir
rm -rf $adir
rm master.zip
